version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: eduportal-mysql
    restart: always
    environment:
      MYSQL_DATABASE: student_management_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: eduportal-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mysqldb

volumes:
  mysql_data:
