ALTER TABLE academic_years MODIFY COLUMN start_year INT NULL;
ALTER TABLE academic_years MODIFY COLUMN end_year INT NULL;
ALTER TABLE subjects MODIFY COLUMN credit INT NULL;

ALTER TABLE credit_classes MODIFY COLUMN semester VARCHAR(10) NULL;
