global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'student-management-backend'
    metrics_path: '/api/v1/actuator/prometheus'
    static_configs:
      - targets: ['backend:8080']
